// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.1
// source: rollercoaster/rollercoaster.proto

package rollercoaster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StationClient is the client API for Station service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StationClient interface {
	// Called by a Wagon. Blocks for the entire ride cycle.
	Departure(ctx context.Context, in *WagonRequest, opts ...grpc.CallOption) (*RideReply, error)
	// Called by a Passenger. Blocks until the ride is over.
	IAmBoarding(ctx context.Context, in *PassengerRequest, opts ...grpc.CallOption) (*RideReply, error)
	// Called by a Passenger after IAmBoarding returns.
	IAmDisembarking(ctx context.Context, in *PassengerRequest, opts ...grpc.CallOption) (*RideReply, error)
}

type stationClient struct {
	cc grpc.ClientConnInterface
}

func NewStationClient(cc grpc.ClientConnInterface) StationClient {
	return &stationClient{cc}
}

func (c *stationClient) Departure(ctx context.Context, in *WagonRequest, opts ...grpc.CallOption) (*RideReply, error) {
	out := new(RideReply)
	err := c.cc.Invoke(ctx, "/rollercoaster.Station/Departure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationClient) IAmBoarding(ctx context.Context, in *PassengerRequest, opts ...grpc.CallOption) (*RideReply, error) {
	out := new(RideReply)
	err := c.cc.Invoke(ctx, "/rollercoaster.Station/IAmBoarding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationClient) IAmDisembarking(ctx context.Context, in *PassengerRequest, opts ...grpc.CallOption) (*RideReply, error) {
	out := new(RideReply)
	err := c.cc.Invoke(ctx, "/rollercoaster.Station/IAmDisembarking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StationServer is the server API for Station service.
// All implementations must embed UnimplementedStationServer
// for forward compatibility
type StationServer interface {
	// Called by a Wagon. Blocks for the entire ride cycle.
	Departure(context.Context, *WagonRequest) (*RideReply, error)
	// Called by a Passenger. Blocks until the ride is over.
	IAmBoarding(context.Context, *PassengerRequest) (*RideReply, error)
	// Called by a Passenger after IAmBoarding returns.
	IAmDisembarking(context.Context, *PassengerRequest) (*RideReply, error)
	mustEmbedUnimplementedStationServer()
}

// UnimplementedStationServer must be embedded to have forward compatible implementations.
type UnimplementedStationServer struct {
}

func (UnimplementedStationServer) Departure(context.Context, *WagonRequest) (*RideReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Departure not implemented")
}
func (UnimplementedStationServer) IAmBoarding(context.Context, *PassengerRequest) (*RideReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IAmBoarding not implemented")
}
func (UnimplementedStationServer) IAmDisembarking(context.Context, *PassengerRequest) (*RideReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IAmDisembarking not implemented")
}
func (UnimplementedStationServer) mustEmbedUnimplementedStationServer() {}

// UnsafeStationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StationServer will
// result in compilation errors.
type UnsafeStationServer interface {
	mustEmbedUnimplementedStationServer()
}

func RegisterStationServer(s grpc.ServiceRegistrar, srv StationServer) {
	s.RegisterService(&Station_ServiceDesc, srv)
}

func _Station_Departure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WagonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationServer).Departure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollercoaster.Station/Departure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationServer).Departure(ctx, req.(*WagonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Station_IAmBoarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationServer).IAmBoarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollercoaster.Station/IAmBoarding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationServer).IAmBoarding(ctx, req.(*PassengerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Station_IAmDisembarking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationServer).IAmDisembarking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollercoaster.Station/IAmDisembarking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationServer).IAmDisembarking(ctx, req.(*PassengerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Station_ServiceDesc is the grpc.ServiceDesc for Station service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Station_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rollercoaster.Station",
	HandlerType: (*StationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Departure",
			Handler:    _Station_Departure_Handler,
		},
		{
			MethodName: "IAmBoarding",
			Handler:    _Station_IAmBoarding_Handler,
		},
		{
			MethodName: "IAmDisembarking",
			Handler:    _Station_IAmDisembarking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollercoaster/rollercoaster.proto",
}
