// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.1
// source: rollercoaster/rollercoaster.proto

// Package name for the generated Go code

package rollercoaster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message for a wagon to identify itself
type WagonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WagonId int32 `protobuf:"varint,1,opt,name=wagon_id,json=wagonId,proto3" json:"wagon_id,omitempty"`
}

func (x *WagonRequest) Reset() {
	*x = WagonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rollercoaster_rollercoaster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WagonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WagonRequest) ProtoMessage() {}

func (x *WagonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollercoaster_rollercoaster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WagonRequest.ProtoReflect.Descriptor instead.
func (*WagonRequest) Descriptor() ([]byte, []int) {
	return file_rollercoaster_rollercoaster_proto_rawDescGZIP(), []int{0}
}

func (x *WagonRequest) GetWagonId() int32 {
	if x != nil {
		return x.WagonId
	}
	return 0
}

// Message for a passenger to identify itself
type PassengerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PassengerId int32 `protobuf:"varint,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
}

func (x *PassengerRequest) Reset() {
	*x = PassengerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rollercoaster_rollercoaster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassengerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassengerRequest) ProtoMessage() {}

func (x *PassengerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollercoaster_rollercoaster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassengerRequest.ProtoReflect.Descriptor instead.
func (*PassengerRequest) Descriptor() ([]byte, []int) {
	return file_rollercoaster_rollercoaster_proto_rawDescGZIP(), []int{1}
}

func (x *PassengerRequest) GetPassengerId() int32 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

// A generic, empty reply to signify success
type RideReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RideReply) Reset() {
	*x = RideReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rollercoaster_rollercoaster_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideReply) ProtoMessage() {}

func (x *RideReply) ProtoReflect() protoreflect.Message {
	mi := &file_rollercoaster_rollercoaster_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideReply.ProtoReflect.Descriptor instead.
func (*RideReply) Descriptor() ([]byte, []int) {
	return file_rollercoaster_rollercoaster_proto_rawDescGZIP(), []int{2}
}

var File_rollercoaster_rollercoaster_proto protoreflect.FileDescriptor

var file_rollercoaster_rollercoaster_proto_rawDesc = []byte{
	0x0a, 0x21, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x63, 0x6f, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2f,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x63, 0x6f, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x63, 0x6f, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x22, 0x29, 0x0a, 0x0c, 0x57, 0x61, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x61, 0x67, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x61, 0x67, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x35, 0x0a,
	0x10, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x32, 0xe5, 0x01, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a,
	0x09, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1b, 0x2e, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x63, 0x6f, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x57, 0x61, 0x67, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x63, 0x6f, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x48, 0x0a, 0x0b, 0x49, 0x41, 0x6d, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x12, 0x1f, 0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x63, 0x6f, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x63, 0x6f, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x0f, 0x49,
	0x41, 0x6d, 0x44, 0x69, 0x73, 0x65, 0x6d, 0x62, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1f,
	0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x63, 0x6f, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x50,
	0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x63, 0x6f, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x63, 0x6f, 0x61, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rollercoaster_rollercoaster_proto_rawDescOnce sync.Once
	file_rollercoaster_rollercoaster_proto_rawDescData = file_rollercoaster_rollercoaster_proto_rawDesc
)

func file_rollercoaster_rollercoaster_proto_rawDescGZIP() []byte {
	file_rollercoaster_rollercoaster_proto_rawDescOnce.Do(func() {
		file_rollercoaster_rollercoaster_proto_rawDescData = protoimpl.X.CompressGZIP(file_rollercoaster_rollercoaster_proto_rawDescData)
	})
	return file_rollercoaster_rollercoaster_proto_rawDescData
}

var file_rollercoaster_rollercoaster_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rollercoaster_rollercoaster_proto_goTypes = []interface{}{
	(*WagonRequest)(nil),     // 0: rollercoaster.WagonRequest
	(*PassengerRequest)(nil), // 1: rollercoaster.PassengerRequest
	(*RideReply)(nil),        // 2: rollercoaster.RideReply
}
var file_rollercoaster_rollercoaster_proto_depIdxs = []int32{
	0, // 0: rollercoaster.Station.Departure:input_type -> rollercoaster.WagonRequest
	1, // 1: rollercoaster.Station.IAmBoarding:input_type -> rollercoaster.PassengerRequest
	1, // 2: rollercoaster.Station.IAmDisembarking:input_type -> rollercoaster.PassengerRequest
	2, // 3: rollercoaster.Station.Departure:output_type -> rollercoaster.RideReply
	2, // 4: rollercoaster.Station.IAmBoarding:output_type -> rollercoaster.RideReply
	2, // 5: rollercoaster.Station.IAmDisembarking:output_type -> rollercoaster.RideReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rollercoaster_rollercoaster_proto_init() }
func file_rollercoaster_rollercoaster_proto_init() {
	if File_rollercoaster_rollercoaster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rollercoaster_rollercoaster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WagonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rollercoaster_rollercoaster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PassengerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rollercoaster_rollercoaster_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rollercoaster_rollercoaster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rollercoaster_rollercoaster_proto_goTypes,
		DependencyIndexes: file_rollercoaster_rollercoaster_proto_depIdxs,
		MessageInfos:      file_rollercoaster_rollercoaster_proto_msgTypes,
	}.Build()
	File_rollercoaster_rollercoaster_proto = out.File
	file_rollercoaster_rollercoaster_proto_rawDesc = nil
	file_rollercoaster_rollercoaster_proto_goTypes = nil
	file_rollercoaster_rollercoaster_proto_depIdxs = nil
}
